name: Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Build Site
        run: |
          yarn install
          yarn build

      - name: Create Extension
        run: |
          cp manifest.json dist/manifest.json

      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "dist"
          zipFilePath: "extensions/chrome-extension-${{ github.event.pull_request.head.sha }}.zip"

      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "extensions/chrome-extension-${{ github.event.pull_request.head.sha }}.zip"
          crxFilePath: "extensions/chrome-extension-${{ github.event.pull_request.head.sha }}.crx"
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}
          path: "extensions/chrome-extension-${{ github.event.pull_request.head.sha }}.crx"
